### ISSUE TITLE
Weapon/Tool Degradation Tweaks

### ISSUE THREAD

**Issue by Novlus-x** [Xanthus58/Better-Vanilla#11]
**Is your feature request related to a problem? Please describe.**
-The weapon/tool degradation is a feature I like a lot, but you have to wait a long time before you even begin to see the weapon/tool degrade at all. I think the weapons/tools should at least begin to degrade a bit sooner, since they only start to degrade when they are in red health.

**Describe the solution you'd like**
-I think weapons/tools should begin to degrade around the 1/4 of health mark and that they should progress in their degradation stages slower.

**Describe alternatives you've considered**
-Change when the weapons start to degrade, and the rate that they degrade at.

**Additional context**
![2021-10-23_18 26 42](https://user-images.githubusercontent.com/91616065/138572092-9b7e8012-966b-4d46-9d04-32501a4657ea.png)
This is a screenshot from when the sword first starts to degrade

**Comment by zephiowl** [comment]
Suggestion has been implemented fully. Degradation now starts earlier and lasts longer.
If your unhappy with the way we changed the pack to add your request you may reopen this ticket.
