### ISSUE TITLE
Stacked Leather Reverts To Orange

### ISSUE THREAD

**Issue by Novlus-x** [Xanthus58/Better-Vanilla#12]
**Describe the bug**
-Leather shows as orange when it is stacked.

**To Reproduce**
1. Go to 'Leather in the in-game inventory'
2. Click on 'Leather'
3. Merge more than one leather together
4. See that the leather switches back to being orange when in a stack

**Expected behavior**
-Leather should stay brown when merged together.

**Screenshots**
![2021-10-23_18 30 11](https://user-images.githubusercontent.com/91616065/138572186-1dbfd9ce-5644-491f-9f8d-34bc94b0897e.png)
You can see the brown leather next to the merged leather and can tell that the stacks of leather become orange

**Additional context**
N/A

**Comment by zephiowl** [comment]
![Base Profile Screenshot 2021 10 27 - 01 36 33 42](https://user-images.githubusercontent.com/66909997/138907397-fadb4e70-0c0c-4cea-98a9-98ab7b092ec0.png)


Fixed
