### ISSUE TITLE
Grass block retexture

### ISSUE THREAD

**Issue by ImNotVeryGoodAtThought** [Xanthus58/Better-Vanilla#4]
It's very simple and understandable (From SINOFSLE002)

![image](https://user-images.githubusercontent.com/88096035/135547480-efe43f7e-aabe-4a73-865f-a849b2b1406f.png)

**Comment by Xanthus58** [comment]
Ahh I see I'll think about implementing that for the next version, don't wanna change the look of the game too much. Its why its mostly models and slight redesigns.

**Comment by ImNotVeryGoodAtThought** [comment]
this isn't what you should copy but used as a example

**Comment by Xanthus58** [comment]
Gotcha

**Comment by ImNotVeryGoodAtThought** [comment]
instead of it covering the block which i personally don't like. the little bit of dirt can have a massive impact of improving the boring designs of grass even if its the same old textures

**Comment by Xanthus58** [comment]
Gotcha my boi; it'll be ready for next release dont worry, already working on it! ty for the suggestion!

**Comment by Xanthus58** [comment]
![Base Profile Screenshot 2021 10 01 - 10 03 51 07](https://user-images.githubusercontent.com/66909997/135548281-f4d11371-964a-4423-9de0-041c373fe88d.png)


its ready for the next update <3
