### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Xanthus58/Better-Vanilla#47]
**Describe the bug**
Reloads constantly and when done it's moved back out.

**To Reproduce**
1. Go to resource packs
2. Click on vanilla renewed
4. Click done
5. See error

**Expected behavior**
I expected it to load in with no problems

**Screenshots**

<img width="966" alt="Screen Shot 2022-10-02 at 3 47 05 PM" src="https://user-images.githubusercontent.com/106651342/193473320-43e85938-212c-4ef3-8463-d5d69fa38d9d.png">

<img width="966" alt="Screen Shot 2022-10-02 at 3 46 41 PM" src="https://user-images.githubusercontent.com/106651342/193473332-0c7cb71e-4802-4501-bbab-bee5b68d8ef6.png">

**Additional context**
Might be conflicting with a mod

**Comment by Aces-and-Jacks** [comment]
Actually maybe it's because I'm just not using optifine and instead of using other mods for fabric that replicate it

**Comment by zephiowl** [comment]
That could very well be the issue as it was designed specifically with optifine. I'll think about putting out a fabric version but right now its not a priority. Let me know if you ended up getting it working either with optifine or some fabric alternative

**Comment by Aces-and-Jacks** [comment]
I was using all the fabric alternative mods I know of at the time so as far as I'm aware fabric alternatives don't work

**Comment by zephiowl** [comment]
@Aces-and-Jacks https://www.curseforge.com/minecraft/mc-mods/optifabric

Try this and see if it works for you; its supposed to run optifine within fabric.

**Comment by Aces-and-Jacks** [comment]
Well it works but optifabric isn't compatible with a lot of the mods that I use

**Comment by Aces-and-Jacks** [comment]
That's the only optifine fabric mod that isn't compatible i think

**Comment by zephiowl** [comment]
If your able to find one that does work be sure to let me know so I can point it to any others that have the same issue

**Comment by Aces-and-Jacks** [comment]
https://lambdaurora.dev/optifine_alternatives/ here's a website that I used as reference. But if any works ill say here
