### ISSUE TITLE
Pickaxe retextures, 

### ISSUE THREAD

**Issue by ImNotVeryGoodAtThought** [Xanthus58/Better-Vanilla#6]
I think  personally tools should look sharper,  axe are fine, pickaxe just looks very blocky when it comes to sharpness, And ill make an example with a pickaxe that's looks like iron pickaxe, this is just a simplistic version. 
![image](https://user-images.githubusercontent.com/88096035/135592278-e0537ac0-8ae7-4ce2-9135-2a3d5f34d36c.png)

**Comment by ImNotVeryGoodAtThought** [comment]
well the only tools are pickaxes, it's not much. just sharpening will give it a nice touch

**Comment by ImNotVeryGoodAtThought** [comment]
_**The problem is with minecraft is it's simple textures that don't make enough sense as pickaxes are more like what is appeared above.**_

**Comment by Xanthus58** [comment]
Definently something I'll consider thank you <3
