### ISSUE TITLE
Arrow Quiver Is Orange

### ISSUE THREAD

**Issue by Novlus-x** [Xanthus58/Better-Vanilla#8]
**Describe the bug**
-> Arrow quiver is orange instead of brown like the rest of the leather items

**To Reproduce**
1. Go to 'The arrow in your in-game inventory'
2. Click on 'Arrow'
3. Merge enough arrows so it shows the quiver
4. See that the quiver is orange and not brown

**Expected behavior**
-> It should be expected that when leather items are supposed to be brown it means ALL leather items

**Screenshots**
![2021-10-23_15 45 09](https://user-images.githubusercontent.com/91616065/138567951-84988589-bfa2-46f8-9028-7472aa3ba6f1.png)
Above you can see the quiver compared to other leather items for reference

**Additional context**
N/A

**Comment by zephiowl** [comment]
![Base Profile Screenshot 2021 10 27 - 01 38 57 80](https://user-images.githubusercontent.com/66909997/138907796-e5a9f231-f8fa-4f17-89bc-ac11cb83e4a9.png)

Has been patched; and is currently implemented in the latest release
